[package]
name = "filefix-hunter"
version = "0.1.0"
edition = "2021"

[dependencies]
winreg = "0.10"
regex = "1"
colored = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.2"